module.exports = {
    1:    { length:   0, name: 'Reference Navigation Data',                    description: 'Not Implemented' },
    2:    { length:  41, name: 'Measured Navigation Data',                     description: 'Position, velocity, and time' },
    3:    { length:   0, name: 'True Tracker Data',                            description: 'Not Implemented' },
    4:    { length: 188, name: 'Measured Tracking Data',                       description: 'Satellite and C/N0 information' },
    5:    { length:   0, name: 'Raw Track Data',                               description: 'Not supported by SiRFstarII' },
    6:    { length:  81, name: 'SW Version',                                   description: 'Receiver software' },
    7:    { length:  20, name: 'Clock Status',                                 description: 'Current clock status' },
    8:    { length:  43,  name: '50 BPS Subframe Data',                         description: 'Standard ICD format' },
    9:    { length:  9,  name: 'Throughput',                                   description: 'Navigation complete data' },
    10:   { name: 'Error ID',                                     description: 'Error coding for message failure' },
    11:   { name: 'Command Acknowledgment',                       description: 'Successful request' },
    12:   { name: 'Command NAcknowledgment',                      description: 'Unsuccessful request' },
    13:   { name: 'Visible List',                                 description: 'Auto Output ' },
    14:   { name: 'Almanac Data',                                 description: 'Response to poll' },
    15:   { name: 'Ephemeris Data',                               description: 'Response to poll' },
    16:   { name: 'Test Mode 1',                                  description: 'For use with SiRFtest (Test Mode 1)' },
    17:   { name: 'Differential Corrections',                     description: 'Received from DGPS broadcast' },
    18:   { name: 'OkToSend',                                     description: 'CPU ON / OFF (TricklePower)' },
    19:   { name: 'Navigation Parameters',                        description: 'Response to Poll' },
    20:   { name: 'Test Mode 2/3/4',                              description: 'Test Mode 2, 3, or 4 test data' },
    27:   { name: 'DGPS Status',                                  description: 'Differential GPS status information' },
    28:   { name: 'Nav. Lib. Measurement Data',                   description: 'Measurement data' },
    29:   { name: 'Nav. Lib. DGPS Data',                          description: 'Differential GPS data' },
    30:   { name: 'Nav. Lib. SV State Data',                      description: 'Satellite state data' },
    31:   { name: 'Nav. Lib. Initialization Data',                description: 'Initialization data' },
    41:   { name: 'Geodetic Navigation Data',                     description: 'Geodetic navigation information' },
    43:   { name: 'Queue Command Parameters',                     description: 'Command parameters' },
    45:   { name: 'Raw DR Data',                                  description: 'Raw DR data from ADC' },
    46:   { name: 'Test Mode 3 & 4 (GSW3 & SLC3)',                description: 'Test data (Test Mode 3 and 4)' },
    //48: { name: 'Test Mode 4 for SiRFLoc v2.x only',            description: 'Test data (Test Mode 4)' },
    48:   { name: 'SiRF Dead Reckoning Class of Output Messages', description: 'The Message ID is partitioned into messages identified by Message Sub IDs, refer to Table 3-2' },
    49:   { name: 'Test Mode 4 for SiRFLoc v2.x only',            description: 'Additional test data (Test Mode 4)' },
    50:   { name: 'SBAS Parameters',                              description: 'SBAS operating parameters' },
    52:   { name: '1 PPS Time Message',                           description: 'Time message for 1 PPS' },
    55:   { name: 'Test Mode 4',                                  description: 'Track Data' },
    56:   { name: 'Extended Ephemeris Data',                      description: 'Extended Ephemeris Mask & Integrity Information' },
    225:  { name: 'SiRF internal message',                        description: 'Reserved' },
    255:  { name: 'Development Data',                             description: 'Various status messages' },
}